### ISSUE TITLE
Allow multiline functions

### ISSUE THREAD

**Issue by fregante** [xojs/stylelint-config-xo#9]
I'd expect at least one of these to work, but I get a lot of errors

```css
tag {
	--background: repeating-linear-gradient(
		45deg,
		var(--github-red),
		var(--github-red) 7px,
		transparent 7px,
		transparent 14px
	) no-repeat;
}
```
```rb
 2:14  ✖  Expected newline after ":" with a multi-line declaration    declaration-colon-newline-after    
 2:42  ✖  Unexpected whitespace after "(" in a multi-line function    function-parentheses-newline-inside
 2:42  ✖  Unexpected whitespace after "("                             function-parentheses-space-inside  
 3:8   ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 3:8   ✖  Expected single space after ","                             function-comma-space-after         
 4:20  ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 4:20  ✖  Expected single space after ","                             function-comma-space-after         
 5:24  ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 5:24  ✖  Expected single space after ","                             function-comma-space-after         
 6:18  ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 6:18  ✖  Expected single space after ","                             function-comma-space-after         
 8:1   ✖  Unexpected whitespace before ")" in a multi-line function   function-parentheses-newline-inside
 8:1   ✖  Unexpected whitespace before ")"                            function-parentheses-space-inside
```
```css
tag {
	--background:
		repeating-linear-gradient(
			45deg,
			var(--github-red),
			var(--github-red) 7px,
			transparent 7px,
			transparent 14px
		) no-repeat;
}
```

```rb
 3:29  ✖  Unexpected whitespace after "(" in a multi-line function    function-parentheses-newline-inside
 3:29  ✖  Unexpected whitespace after "("                             function-parentheses-space-inside  
 4:9   ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 4:9   ✖  Expected single space after ","                             function-comma-space-after         
 5:21  ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 5:21  ✖  Expected single space after ","                             function-comma-space-after         
 6:25  ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 6:25  ✖  Expected single space after ","                             function-comma-space-after         
 7:19  ✖  Unexpected whitespace after "," in a multi-line function    function-comma-newline-after       
 7:19  ✖  Expected single space after ","                             function-comma-space-after         
 9:2   ✖  Unexpected whitespace before ")" in a multi-line function   function-parentheses-newline-inside
 9:2   ✖  Unexpected whitespace before ")"                            function-parentheses-space-inside
```

Suggestions?

**Comment by fregante** [comment]
For the record, Prettier suggests this:

```css
tag {
	--background: repeating-linear-gradient(
			45deg,
			var(--github-red),
			var(--github-red) 7px,
			transparent 7px,
			transparent 14px
		)
		no-repeat;
}
```

**Comment by fregante** [comment]
This is the suggested override:

```json
{
	"function-parentheses-newline-inside": "always-multi-line",
	"function-parentheses-space-inside": "never-single-line",
	"function-comma-newline-after": "always-multi-line",
	"function-comma-space-after": "always-single-line"
}
```

It allows:

```css
tag {
	--background:
		repeating-linear-gradient(
			45deg,
			var(--github-red),
			var(--github-red) 7px,
			transparent 7px,
			transparent 14px
		) no-repeat;
}
```

Live demo: https://github.com/sindresorhus/refined-github/pull/3053/commits/fae0c7ef7deb2622b7d9e54c89a8f07e43098247
